name: 'Code Digest Generator'
description: 'Generate a comprehensive digest of your codebase, including directory trees and file statistics'
author: 'Diego Maroto'

branding:
  icon: 'file-text'
  color: 'gray-dark'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
    type: string

  directory:
    description: 'Directory to analyze'
    required: false
    default: '.'
    type: string

  output-dir:
    description: 'Output directory for generated files'
    required: false
    default: 'code-digest-output'
    type: string

  ignore-patterns:
    description: 'Additional patterns to ignore (comma separated)'
    required: false
    default: ''
    type: string

  gitignore-path:
    description: 'Path to custom .gitignore file'
    required: false
    default: '.gitignore'
    type: string

  max-file-size:
    description: 'Maximum file size in MB'
    required: false
    default: '10'
    type: string

  include-binary:
    description: 'Include binary files in the digest'
    required: false
    default: 'false'
    type: string

  include-dot:
    description: 'Include dot files in the tree'
    required: false
    default: 'false'
    type: string

  output-format:
    description: 'Output format (json, text, or both)'
    required: false
    default: 'text'
    type: string

  retention-days:
    description: 'Number of days to retain artifacts'
    required: false
    default: '90'
    type: string

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Create Digest
      shell: bash
      run: |
        node build/code-digest.js \
          --directory "${{ inputs.directory }}" \
          --output "${{ inputs.output-dir }}" \
          --ignore "${{ inputs.ignore-patterns }}" \
          --gitignore "${{ inputs.gitignore-path }}" \
          --max-size "${{ inputs.max-file-size }}" \
          ${{ inputs.include-binary == "true" && '--include-binary' }} \
          ${{ inputs.include-dot == "true" && '--include-dot' }} \
          --format "${{ inputs.output-format }}"

    - name: Upload Digest Files
      uses: actions/upload-artifact@v4
      with:
        name: code-digest-files
        path: ${{ inputs.output-dir }}
        retention-days: ${{ inputs.retention-days }}
