name: Generate Code Digest
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Code Digest
        uses: diego-maroto/code-digest-generator@${{ github.ref_name }}
        with:
          directory: 'lib'
          output-format: 'text'
          retention-days: '7'
