name: Example Code Digest
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Code Digest
        uses: diekotto/code-digest-action@main
        with:
          directory: 'lib'
          output-format: 'text'
          retention-days: '7'
